name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build seed0
        run: |
          cd src/seed0
          make

      - name: run examples
        run: |
          cd src/seed0
          ./astralis ../../examples/hello.astr
          printf "Astralis\n" | ./astralis ../../examples/vars.astr
          cd ../..
          ./tools/run_examples.sh
